Models/AppDbContext.cs
using System.Data.Entity;

namespace DemoEPS.Models
{
    
    public class AppDbContext : DbContext
    {
        public DbSet<Coupon> Coupons { get; set; }

        public AppDbContext() : base("DefaultConnection") { }
    }
}

Models/Coupon.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace DemoEPS.Models
{
    public class Coupon
    {
        public int Id { get; set; }

        [Required]
        public string Code { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;

        public bool IsSent { get; set; } = false;

        [Range(0, 100)]
        public int DiscountPercentage { get; set; } = 10;

        public DateTime? ExpiryDate { get; set; }
    }

    public class CouponModel
    {
        public int Id { get; set; }

        [Required]
        public string Code { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;

        public bool IsUsed { get; set; } = false;

        [Range(0, 100)]
        public int DiscountPercentage { get; set; } = 10;

        public int NumberOfDiscountCoupon { get; set; } = 1;

        public DateTime? ExpiryDate { get; set; }
    }

    public class APIResponseModel
    {
        public bool Status { get; set; }
        public int Code { get; set; }
        public string Message { get; set; }
    }
}

Controllers/CouponController.cs
using DemoEPS.Models;
using System;
using System.Linq;
using System.Web.Mvc;

public class CouponController : Controller
{
    private AppDbContext db = new AppDbContext();

    public ActionResult Index()
    {
        return View(db.Coupons.ToList());
    }

    public ActionResult Create()
    {
        CouponModel couponModel = new CouponModel();
        return View(couponModel);
    }

    [HttpPost]
    public ActionResult Create(CouponModel couponModel)
    {
        for (int i = 0; i < couponModel.NumberOfDiscountCoupon; i++)
        {
            Coupon coupon = new Coupon();
            coupon.Code = GenerateCouponCode();
            coupon.ExpiryDate = couponModel.ExpiryDate;
            coupon.DiscountPercentage = couponModel.DiscountPercentage;
            db.Coupons.Add(coupon);
            db.SaveChanges();
        }

        return RedirectToAction("Index", new { msg = "Coupon created successfully" });
    }

    private string GenerateCouponCode()
    {
        var guid = Guid.NewGuid().ToString("N").Substring(0, 8).ToUpper();
        return $"{guid}";
    }

    public ActionResult SendCouponCode(string code)
    {
        var coupon = db.Coupons.Where(c => string.Compare(c.Code, code, true) == 0).FirstOrDefault();
        if (coupon != null)
        {
            coupon.IsSent = true;
            db.SaveChanges();
        }

        return RedirectToAction("Index", new { msg = "Coupon sent successfully" });
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoEPS.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Views/Coupon/Create.cshtml
@model DemoEPS.Models.CouponModel
@{
    ViewBag.Title = "Create Coupon";
}
<h2>Create Coupon</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-group">
            Number Of Discount Coupon
            @Html.EditorFor(m => m.NumberOfDiscountCoupon)
            <br />
            <br />
            Discount Percentage
            @Html.EditorFor(m => m.DiscountPercentage)
            @Html.ValidationMessageFor(m => m.DiscountPercentage)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ExpiryDate)
            @Html.TextBoxFor(m => m.ExpiryDate, "{0:yyyy-MM-dd}", new { type = "date" })
        </div>
        <button type="submit" class="btn btn-primary">Generate</button>
    </div>
}

Views/Coupon/Index.cshtml
@model IEnumerable<DemoEPS.Models.Coupon>
@{
    ViewBag.Title = "Coupons";
}
@if (Request.QueryString["msg"] != null)
{
    <div>
        @Request.QueryString["msg"].ToString()
    </div>
}

<h2>All Coupons</h2>
<p>@Html.ActionLink("Create New Coupon", "Create")</p>
<table class="table">
    <tr>
        <th>Code</th>
        <th>Discount %</th>
        <th>Is Sent</th>
        <th>Expires</th>
        <th>Send coupon</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Code</td>
            <td>@item.DiscountPercentage</td>
            <td>@item.IsSent</td>
            <td>@item.ExpiryDate.Value.ToString("yyyy-MM-dd")</td>
            @if (!item.IsSent)
            {
                <td><input type="button" value="Send" onclick='window.location.href = "@Url.Action("SendCouponCode", "Coupon", new { code = @item.Code })";' /></td>
            }
        </tr>
    }
</table>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Coupon", "Index", "Coupon")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>